---

- name: Provision a {{ application_name }} web server
  hosts: webservers
  become: yes
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - env_vars/{{ env }}_django_secrets.yml

  roles:
    - { role: base, create_swap_file: yes }
    - certbot
    - nginx
    - uwsgi
    - postgres
    - web
