---

# Nginx settings (nginx)
static_base: "/media/{{ application_name }}/{{ project_env }}"
nginx_static_dir: "{{ static_base }}/static/"
nginx_media_dir: "{{ static_base }}/media/"
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"


# Project Name (base)
project_name: mmpl-site
application_name: mmpl


# Date / Time settings (base)
timezone: Australia/Melbourne


# Application settings. (base)
project_env: production
project_path: "/var/www/{{ application_name }}/{{ project_env }}"
application_log_dir: "/var/log/{{ application_name }}"
git_repo_path: "{{ project_path }}/repo"
app_template_path: "{{ project_path }}/templates"
virtualenv_path: "{{ project_path }}/venv"
requirements_file: "{{ git_repo_path }}/site/requirements.txt"


# Swap file settings (base)
create_swap_file: yes


# Webapp settings (base|$webapp)
webapp_user: "{{ application_name }}"
webapp_group: webapps
