---

- name: Place 404, 500 and maintenance pages
  template:
    src: "{{ item }}.j2"
    dest: "{{ app_template_path }}/{{ item }}.html"
    backup: yes
  with_items:
    - "404"
    - "500"
    - "maintenance_on"
