---

- name: Create the application user
  user: name={{ webapp_user }} state=present

- name: Create the application group
  group: name={{ webapp_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ webapp_user }} group={{ webapp_group }} state=present
