---

- name: Setup 0755 Directories.
  file:
    path: "{{ item }}"
    recurse: yes
    owner: "{{ webapp_user }}"
    group: "{{ webapp_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ nginx_static_dir }}"
    - "{{ nginx_media_dir }}"
    - "{{ project_path }}"
    - "{{ app_template_path }}"
    - "{{ gmaps_image_dir }}"

- name: Setup 0770 Directories.
  file:
    path: "{{ item }}"
    recurse: yes
    owner: "{{ webapp_user }}"
    group: "{{ webapp_group }}"
    state: directory
    mode: 0770
  with_items:
    - "{{ nginx_log_dir }}"
    - "{{ uwsgi_log_dir }}"
    - "{{ django_log_dir }}"

- name: Touch Django Log File
  file:
    path: "{{ django_log_dir }}/mmpl.log"
    owner: "{{ webapp_user }}"
    group: "{{ webapp_group }}"
    state: touch
    mode: 0770